/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import controlador.Ctrl_login;
import java.awt.CardLayout;
import java.awt.Dimension;
import javax.swing.JMenu;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import utils.Sesion;

/**
 *
 * @author jhona
 */
public class Menu extends javax.swing.JFrame {

//    Panel_GestionarUsuarios panelUsuario = new Panel_GestionarUsuarios();
//    CardLayout panel;

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }
    
    public JMenuItem getDashboardInicial() {
    return dashboardInicial;
}
    
    public JMenuItem getCerrarSesion() {
    return cerrarSesion;
}
 
    public JMenuItem getRegistrarUsuario() {
    return registrarUsuario;
}

    public JMenuItem getGestionarUsuario() {
    return gestionarUsuario;
}

    public JMenuItem getGestionarMascotas() {
    return gestionarMascota;
}
        
    public JMenuItem getGestionarCitas() {
    return gestionarCitas;
}
    
    public JMenuItem getRegistrarCita() {
    return registrarCita;
}
            
    public JPanel getPanelVistaPrincipal() {
    return panelVistaPrincipal;
}
    
    public JMenu getMenuUsuarios() {
    return menuUsuarios;
}
    
private void btnCerrarSesionActionPerformed() {
    int confirm = JOptionPane.showConfirmDialog(
        this,
        "¿Está seguro que desea cerrar la sesión?",
        "Confirmar cierre de sesión",
        JOptionPane.YES_NO_OPTION,
        JOptionPane.QUESTION_MESSAGE
    );
    
    if (confirm == JOptionPane.YES_OPTION) {
        try {
            // 1. Cerrar la sesión
            Sesion.getInstancia().cerrarSesion();
            
            System.out.println("Sesión cerrada correctamente");
            
            // 2. Cerrar el menú actual
            this.dispose();
            
            // 3. Crear una NUEVA ventana de login con su controlador
            java.awt.EventQueue.invokeLater(() -> {
                Login login = new Login();
                Ctrl_login controladorLogin = new Ctrl_login(login);
                login.setVisible(true);
                login.setLocationRelativeTo(null);
            });
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(
                this,
                "Error al cerrar sesión: " + e.getMessage(),
                "Error",
                JOptionPane.ERROR_MESSAGE
            );
            e.printStackTrace();
        }
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelVistaPrincipal = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        dashboardInicial = new javax.swing.JMenuItem();
        cerrarSesion = new javax.swing.JMenuItem();
        menuUsuarios = new javax.swing.JMenu();
        registrarUsuario = new javax.swing.JMenuItem();
        gestionarUsuario = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        gestionarMascota = new javax.swing.JMenuItem();
        menuCitas = new javax.swing.JMenu();
        registrarCita = new javax.swing.JMenuItem();
        gestionarCitas = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1920, 1080));

        panelVistaPrincipal.setBackground(new java.awt.Color(204, 204, 255));

        javax.swing.GroupLayout panelVistaPrincipalLayout = new javax.swing.GroupLayout(panelVistaPrincipal);
        panelVistaPrincipal.setLayout(panelVistaPrincipalLayout);
        panelVistaPrincipalLayout.setHorizontalGroup(
            panelVistaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1080, Short.MAX_VALUE)
        );
        panelVistaPrincipalLayout.setVerticalGroup(
            panelVistaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );

        jMenu1.setText("Inicio");

        dashboardInicial.setText("Dashboard Inicio");
        jMenu1.add(dashboardInicial);

        cerrarSesion.setText("Cerrar Sesion");
        cerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarSesionActionPerformed(evt);
            }
        });
        jMenu1.add(cerrarSesion);

        jMenuBar1.add(jMenu1);

        menuUsuarios.setText("Usuarios");

        registrarUsuario.setText("Registrar Usuario");
        menuUsuarios.add(registrarUsuario);

        gestionarUsuario.setText("Gestionar Usuarios");
        menuUsuarios.add(gestionarUsuario);

        jMenuBar1.add(menuUsuarios);

        jMenu2.setText("Mascotas");

        gestionarMascota.setText("Gestionar Mascotas");
        jMenu2.add(gestionarMascota);

        jMenuBar1.add(jMenu2);

        menuCitas.setText("Citas");

        registrarCita.setText("Agendar Cita");
        menuCitas.add(registrarCita);

        gestionarCitas.setText("Gestionar Citas");
        menuCitas.add(gestionarCitas);

        jMenuBar1.add(menuCitas);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelVistaPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelVistaPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarSesionActionPerformed
        btnCerrarSesionActionPerformed();     // TODO add your handling code here:
    }//GEN-LAST:event_cerrarSesionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem cerrarSesion;
    private javax.swing.JMenuItem dashboardInicial;
    private javax.swing.JMenuItem gestionarCitas;
    private javax.swing.JMenuItem gestionarMascota;
    public javax.swing.JMenuItem gestionarUsuario;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu menuCitas;
    private javax.swing.JMenu menuUsuarios;
    public javax.swing.JPanel panelVistaPrincipal;
    private javax.swing.JMenuItem registrarCita;
    public javax.swing.JMenuItem registrarUsuario;
    // End of variables declaration//GEN-END:variables
}
