/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import java.awt.CardLayout;
import java.awt.Dimension;
import javax.swing.JMenu;
import javax.swing.JMenuItem;
import javax.swing.JPanel;

/**
 *
 * @author jhona
 */
public class Menu extends javax.swing.JFrame {

//    Panel_GestionarUsuarios panelUsuario = new Panel_GestionarUsuarios();
//    CardLayout panel;

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }
    

 
    public JMenuItem getRegistrarUsuario() {
    return registrarUsuario;
}

    public JMenuItem getGestionarUsuario() {
    return gestionarUsuario;
}

    public JMenuItem getGestionarMascotas() {
    return gestionarMascota;
}
        
    public JMenuItem getGestionarCitas() {
    return gestionarCitas;
}
            
    public JPanel getPanelVistaPrincipal() {
    return panelVistaPrincipal;
}
    
    public JMenu getMenuUsuarios() {
    return menuUsuarios;
}
    


    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelVistaPrincipal = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuUsuarios = new javax.swing.JMenu();
        registrarUsuario = new javax.swing.JMenuItem();
        gestionarUsuario = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        gestionarMascota = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        gestionarCitas = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1920, 1080));
        setMinimumSize(new java.awt.Dimension(1920, 1080));
        setPreferredSize(new java.awt.Dimension(1920, 1080));

        panelVistaPrincipal.setBackground(new java.awt.Color(204, 204, 255));

        javax.swing.GroupLayout panelVistaPrincipalLayout = new javax.swing.GroupLayout(panelVistaPrincipal);
        panelVistaPrincipal.setLayout(panelVistaPrincipalLayout);
        panelVistaPrincipalLayout.setHorizontalGroup(
            panelVistaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1080, Short.MAX_VALUE)
        );
        panelVistaPrincipalLayout.setVerticalGroup(
            panelVistaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );

        menuUsuarios.setText("Usuarios");

        registrarUsuario.setText("Registrar Usuario");
        menuUsuarios.add(registrarUsuario);

        gestionarUsuario.setText("Gestionar Usuarios");
        menuUsuarios.add(gestionarUsuario);

        jMenuBar1.add(menuUsuarios);

        jMenu2.setText("Mascotas");

        jMenuItem1.setText("Registrar Mascosta");
        jMenu2.add(jMenuItem1);

        gestionarMascota.setText("Gestionar Mascotas");
        jMenu2.add(gestionarMascota);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Citas");

        jMenuItem3.setText("Agendar Cita");
        jMenu3.add(jMenuItem3);

        gestionarCitas.setText("Gestionar Citas");
        jMenu3.add(gestionarCitas);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Consultas");
        jMenuBar1.add(jMenu4);

        jMenu5.setText("Veterinarios");
        jMenuBar1.add(jMenu5);

        jMenu6.setText("Configuracion");
        jMenuBar1.add(jMenu6);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelVistaPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelVistaPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem gestionarCitas;
    private javax.swing.JMenuItem gestionarMascota;
    public javax.swing.JMenuItem gestionarUsuario;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenu menuUsuarios;
    public javax.swing.JPanel panelVistaPrincipal;
    public javax.swing.JMenuItem registrarUsuario;
    // End of variables declaration//GEN-END:variables
}
