package vista;

import controlador.Ctrl_Consulta;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import modelo.Cita;
import modelo.CitaDAO;

public class Panel_RegistrarConsulta extends javax.swing.JPanel {

//    public Panel_RegistrarConsulta() {
//        initComponents();
//    }

    private int idCita;
    private Cita cita;
    private Ctrl_Consulta ctrlConsulta;
    private Runnable onSuccess; // Callback para cuando se complete la acción
    
    // Constructor con parámetros
   public Panel_RegistrarConsulta(int idCita, Runnable onSuccess) {
        this.idCita = idCita;
        this.onSuccess = onSuccess;
        this.ctrlConsulta = new Ctrl_Consulta();
        this.cita = new CitaDAO().buscarPorId(idCita);
        initComponents();
        cargarDatosCita();
        configurarEventos();
    }
    
    // Constructor vacío para compatibilidad con NetBeans
    public Panel_RegistrarConsulta() {
        this(0, null);
    }
    
    private void configurarEventos() {
        btnRegistrarConsulta.addActionListener(e -> registrarConsulta());
        btnCancelarRegistroConsulta.addActionListener(e -> cancelar());
    }
    
    private void cargarDatosCita() {
        if (cita != null) {
            SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy HH:mm");
            labelMascotaResultado.setText(cita.getNombreMascota());
            labelDuenoResultado.setText(cita.getNombreCliente());
            labelFechaHoraResultado.setText(sdf.format(cita.getFechaHora()));
            labelVeterinarioResultado.setText(cita.getNombreVeterinario());
        } else {
            labelMascotaResultado.setText("No encontrada");
            labelDuenoResultado.setText("No encontrada");
            labelFechaHoraResultado.setText("No encontrada");
            labelVeterinarioResultado.setText("No encontrada");
            btnRegistrarConsulta.setEnabled(false);
        }
    }
    
    private void registrarConsulta() {
        String diagnostico = textAreaDiagnostico.getText().trim();
        String tratamiento = textAreaTratamiento.getText().trim();
        String observaciones = textAreaObservaciones.getText().trim();
        
        // Validación
        if (diagnostico.isEmpty()) {
            JOptionPane.showMessageDialog(this, 
                "El diagnóstico es obligatorio.", 
                "Validación", 
                JOptionPane.WARNING_MESSAGE);
            textAreaDiagnostico.requestFocus();
            return;
        }
        
        // Confirmar antes de registrar
        int confirm = JOptionPane.showConfirmDialog(this,
            "¿Está seguro de registrar esta consulta médica?\n" +
            "Una vez registrada, la cita quedará como completada.",
            "Confirmar registro",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.QUESTION_MESSAGE);
        
        if (confirm != JOptionPane.YES_OPTION) {
            return;
        }
        
        // Registrar consulta
        boolean exito = ctrlConsulta.registrarConsulta(idCita, diagnostico, tratamiento, observaciones);
        
        if (exito) {
            if (onSuccess != null) {
                onSuccess.run();
            }
        }
    }
    
    private void cancelar() {
        int confirm = JOptionPane.showConfirmDialog(this,
            "¿Desea cancelar el registro de consulta?\n" +
            "Los datos ingresados se perderán.",
            "Confirmar cancelación",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.WARNING_MESSAGE);
        
        if (confirm == JOptionPane.YES_OPTION && onSuccess != null) {
            onSuccess.run();
        }
    }
    
    // Método para obtener el ID de la cita actual
    public int getIdCita() {
        return idCita;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        labelDiagnostico = new javax.swing.JLabel();
        labelTratamiento = new javax.swing.JLabel();
        jScrollPane = new javax.swing.JScrollPane();
        textAreaObservaciones = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        textAreaTratamiento = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        textAreaDiagnostico = new javax.swing.JTextArea();
        labelObservaciones = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        labelMascota = new javax.swing.JLabel();
        labelDueno = new javax.swing.JLabel();
        labelVeterinario = new javax.swing.JLabel();
        labelFechaHora = new javax.swing.JLabel();
        labelVeterinarioResultado = new javax.swing.JLabel();
        labelMascotaResultado = new javax.swing.JLabel();
        labelDuenoResultado = new javax.swing.JLabel();
        labelFechaHoraResultado = new javax.swing.JLabel();
        btnCancelarRegistroConsulta = new javax.swing.JButton();
        btnRegistrarConsulta = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Registro de Consulta"));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos de la consulta"));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelDiagnostico.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        labelDiagnostico.setForeground(new java.awt.Color(51, 51, 51));
        labelDiagnostico.setText("Diagnóstico:*");
        jPanel2.add(labelDiagnostico, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, 30));

        labelTratamiento.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        labelTratamiento.setForeground(new java.awt.Color(51, 51, 51));
        labelTratamiento.setText("Tratamiento:");
        jPanel2.add(labelTratamiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, 30));

        textAreaObservaciones.setColumns(20);
        textAreaObservaciones.setRows(5);
        jScrollPane.setViewportView(textAreaObservaciones);

        jPanel2.add(jScrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 70, 390, 270));

        textAreaTratamiento.setColumns(20);
        textAreaTratamiento.setRows(5);
        jScrollPane1.setViewportView(textAreaTratamiento);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 470, 100));

        textAreaDiagnostico.setColumns(20);
        textAreaDiagnostico.setRows(5);
        jScrollPane2.setViewportView(textAreaDiagnostico);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 470, 130));

        labelObservaciones.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        labelObservaciones.setForeground(new java.awt.Color(51, 51, 51));
        labelObservaciones.setText("Observaciones:");
        jPanel2.add(labelObservaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 30, -1, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 990, 360));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Informacion de la Cita"));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelMascota.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        labelMascota.setForeground(new java.awt.Color(51, 51, 51));
        labelMascota.setText("Mascota:");
        jPanel3.add(labelMascota, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, 30));

        labelDueno.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        labelDueno.setForeground(new java.awt.Color(51, 51, 51));
        labelDueno.setText("Dueño:");
        jPanel3.add(labelDueno, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, 30));

        labelVeterinario.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        labelVeterinario.setForeground(new java.awt.Color(51, 51, 51));
        labelVeterinario.setText("Veterinario:");
        jPanel3.add(labelVeterinario, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, 30));

        labelFechaHora.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        labelFechaHora.setForeground(new java.awt.Color(51, 51, 51));
        labelFechaHora.setText("Fecha y hora:");
        jPanel3.add(labelFechaHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, 30));

        labelVeterinarioResultado.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        labelVeterinarioResultado.setForeground(new java.awt.Color(51, 51, 51));
        labelVeterinarioResultado.setText("-");
        jPanel3.add(labelVeterinarioResultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 160, 220, 30));

        labelMascotaResultado.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        labelMascotaResultado.setForeground(new java.awt.Color(51, 51, 51));
        labelMascotaResultado.setText("-");
        jPanel3.add(labelMascotaResultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, 220, 30));

        labelDuenoResultado.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        labelDuenoResultado.setForeground(new java.awt.Color(51, 51, 51));
        labelDuenoResultado.setText("-");
        jPanel3.add(labelDuenoResultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, 220, 30));

        labelFechaHoraResultado.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        labelFechaHoraResultado.setForeground(new java.awt.Color(51, 51, 51));
        labelFechaHoraResultado.setText("-");
        jPanel3.add(labelFechaHoraResultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, 220, 30));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 450, 220));

        btnCancelarRegistroConsulta.setBackground(new java.awt.Color(255, 51, 51));
        btnCancelarRegistroConsulta.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        btnCancelarRegistroConsulta.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelarRegistroConsulta.setText("Cancelar");
        jPanel1.add(btnCancelarRegistroConsulta, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 210, 110, 30));

        btnRegistrarConsulta.setBackground(new java.awt.Color(82, 215, 82));
        btnRegistrarConsulta.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        btnRegistrarConsulta.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrarConsulta.setText("Registrar Consulta");
        jPanel1.add(btnRegistrarConsulta, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 210, 180, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnCancelarRegistroConsulta;
    public javax.swing.JButton btnRegistrarConsulta;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelDiagnostico;
    private javax.swing.JLabel labelDueno;
    private javax.swing.JLabel labelDuenoResultado;
    private javax.swing.JLabel labelFechaHora;
    private javax.swing.JLabel labelFechaHoraResultado;
    private javax.swing.JLabel labelMascota;
    private javax.swing.JLabel labelMascotaResultado;
    private javax.swing.JLabel labelObservaciones;
    private javax.swing.JLabel labelTratamiento;
    private javax.swing.JLabel labelVeterinario;
    private javax.swing.JLabel labelVeterinarioResultado;
    private javax.swing.JTextArea textAreaDiagnostico;
    private javax.swing.JTextArea textAreaObservaciones;
    private javax.swing.JTextArea textAreaTratamiento;
    // End of variables declaration//GEN-END:variables
}
