package vista;

import com.toedter.calendar.JDateChooser;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.JTextArea;


public class Panel_RegistrarCitas extends javax.swing.JPanel {

    /**
     * Creates new form Panel_RegistrarCitas
     */
    public Panel_RegistrarCitas() {
        initComponents();
    }

    public JComboBox getComboMascota() {
        return comboMascota;
    }

    public JComboBox getComboEspecialidad() {
        return comboEspecialidad;
    }

    public JComboBox getComboHora() {
        return comboHora;
    }

    public JTextArea getTextMotivo() {
        return textAreaMotivo;
    }

    public JDateChooser getDateFecha() {
        return fecha;
    }

    public JLabel getLabelPropietario() {
        return labelEspecialidad;
    }

    public JButton getBtn_limpiar() {
        return btn_limpiar;
    }

    public JButton getBtn_resgistrarCita() {
        return btn_registrarCita;
    }

    public JTable getTablaCitas() {
        return tablaCita;
    }

    /**
     *
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        comboHora = new javax.swing.JComboBox<>();
        labelHora = new javax.swing.JLabel();
        labelEspecialidad = new javax.swing.JLabel();
        comboEspecialidad = new javax.swing.JComboBox<>();
        labelMotivo = new javax.swing.JLabel();
        labelMascota = new javax.swing.JLabel();
        comboMascota = new javax.swing.JComboBox<>();
        jScrollPane = new javax.swing.JScrollPane();
        textAreaMotivo = new javax.swing.JTextArea();
        labelFecha = new javax.swing.JLabel();
        btn_registrarCita = new javax.swing.JButton();
        btn_limpiar = new javax.swing.JButton();
        jScrollTable = new javax.swing.JScrollPane();
        tablaCita = new javax.swing.JTable();
        fecha = new com.toedter.calendar.JDateChooser();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Registro de Citas"));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        comboHora.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jPanel1.add(comboHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 170, 190, 30));

        labelHora.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        labelHora.setForeground(new java.awt.Color(51, 51, 51));
        labelHora.setText("Hora:");
        jPanel1.add(labelHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 130, -1, 30));

        labelEspecialidad.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        labelEspecialidad.setForeground(new java.awt.Color(51, 51, 51));
        labelEspecialidad.setText("Especialidad:");
        jPanel1.add(labelEspecialidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, 30));

        comboEspecialidad.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jPanel1.add(comboEspecialidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 190, 30));

        labelMotivo.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        labelMotivo.setForeground(new java.awt.Color(51, 51, 51));
        labelMotivo.setText("Motivo de consulta:");
        jPanel1.add(labelMotivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 50, -1, 30));

        labelMascota.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        labelMascota.setForeground(new java.awt.Color(51, 51, 51));
        labelMascota.setText("Mascota:");
        jPanel1.add(labelMascota, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, 30));

        comboMascota.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jPanel1.add(comboMascota, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 190, 30));

        textAreaMotivo.setColumns(20);
        textAreaMotivo.setRows(5);
        jScrollPane.setViewportView(textAreaMotivo);

        jPanel1.add(jScrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 90, 340, 110));

        labelFecha.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        labelFecha.setForeground(new java.awt.Color(51, 51, 51));
        labelFecha.setText("Fecha:");
        jPanel1.add(labelFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 40, -1, 30));

        btn_registrarCita.setBackground(new java.awt.Color(0, 161, 199));
        btn_registrarCita.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        btn_registrarCita.setForeground(new java.awt.Color(255, 255, 255));
        btn_registrarCita.setText("Agendar cita");
        jPanel1.add(btn_registrarCita, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 150, 30));

        btn_limpiar.setBackground(new java.awt.Color(0, 161, 199));
        btn_limpiar.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        btn_limpiar.setForeground(new java.awt.Color(255, 255, 255));
        btn_limpiar.setText("Limpiar Campos");
        jPanel1.add(btn_limpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 240, 140, 30));

        tablaCita.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        tablaCita.setForeground(new java.awt.Color(51, 51, 51));
        tablaCita.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Cita", "Mascota", "Veterinario", "Especialidad", "Fecha y Hora", "Estado"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaCita.setRowHeight(30);
        tablaCita.setSelectionBackground(new java.awt.Color(191, 232, 241));
        tablaCita.getTableHeader().setResizingAllowed(false);
        tablaCita.getTableHeader().setReorderingAllowed(false);
        jScrollTable.setViewportView(tablaCita);

        jPanel1.add(jScrollTable, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 1000, 380));
        jPanel1.add(fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 80, 230, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1040, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 680, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btn_limpiar;
    public javax.swing.JButton btn_registrarCita;
    public javax.swing.JComboBox<Object> comboEspecialidad;
    public javax.swing.JComboBox<Object> comboHora;
    public javax.swing.JComboBox<Object> comboMascota;
    private com.toedter.calendar.JDateChooser fecha;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JScrollPane jScrollTable;
    private javax.swing.JLabel labelEspecialidad;
    private javax.swing.JLabel labelFecha;
    private javax.swing.JLabel labelHora;
    private javax.swing.JLabel labelMascota;
    private javax.swing.JLabel labelMotivo;
    public javax.swing.JTable tablaCita;
    private javax.swing.JTextArea textAreaMotivo;
    // End of variables declaration//GEN-END:variables
}
