package vista.dashboard;

import javax.swing.JLabel;

public class DashboardVeterinario extends javax.swing.JPanel {

    public DashboardVeterinario() {
        initComponents();
        inicializarValores();
    }
    
    private void inicializarValores() {
        citasPendientesVet.setText("0");
        citasCompletadasVet.setText("0");
        mascotasAtendidasVet.setText("0");
    }
    
    // Getters para los labels (necesarios para el controlador)
    public JLabel getCitasPendientesVet() {
        return citasPendientesVet;
    }
    
    public JLabel getCitasCompletadasVet() {
        return citasCompletadasVet;
    }
    
    public JLabel getMascotasAtendidasVet() {
        return mascotasAtendidasVet;
    }
    
    // Método para actualizar todos los datos de una vez
    public void actualizarDatos(int citasPendientes, int citasCompletadas, int mascotasAtendidas) {
        citasPendientesVet.setText(String.valueOf(citasPendientes));
        citasCompletadasVet.setText(String.valueOf(citasCompletadas));
        mascotasAtendidasVet.setText(String.valueOf(mascotasAtendidas));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        citasPendientesVet = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        citasCompletadasVet = new javax.swing.JLabel();
        mascotasAtendidasVet = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 153, 255));
        jLabel4.setText("Total Mascotas Atendidas");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 210, -1, -1));

        citasPendientesVet.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        citasPendientesVet.setForeground(new java.awt.Color(0, 153, 255));
        citasPendientesVet.setText("-------");
        add(citasPendientesVet, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 153, 255));
        jLabel6.setText("Citas Completadas Asignadas");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 60, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 153, 255));
        jLabel7.setText("Citas Pendientes Asignadas");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, -1, -1));

        citasCompletadasVet.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        citasCompletadasVet.setForeground(new java.awt.Color(0, 153, 255));
        citasCompletadasVet.setText("-------");
        add(citasCompletadasVet, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 100, -1, -1));

        mascotasAtendidasVet.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        mascotasAtendidasVet.setForeground(new java.awt.Color(0, 153, 255));
        mascotasAtendidasVet.setText("-------");
        add(mascotasAtendidasVet, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 260, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel citasCompletadasVet;
    private javax.swing.JLabel citasPendientesVet;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel mascotasAtendidasVet;
    // End of variables declaration//GEN-END:variables
}
