package vista.dashboard;

import javax.swing.JLabel;

public class DashboardCliente extends javax.swing.JPanel {

public DashboardCliente() {
        initComponents();
        inicializarValores();
    }
    
    private void inicializarValores() {
        citasPendientesCli.setText("0");
        citasCompletasCli.setText("0");
        totalMascotasCli.setText("0");
    }
    
    // Getters para los labels (necesarios para el controlador)
    public JLabel getCitasPendientesCli() {
        return citasPendientesCli;
    }
    
    public JLabel getCitasCompletasCli() {
        return citasCompletasCli;
    }
    
    public JLabel getTotalMascotasCli() {
        return totalMascotasCli;
    }
    
    // Método para actualizar todos los datos de una vez
    public void actualizarDatos(int citasPendientes, int citasCompletadas, int totalMascotas) {
        citasPendientesCli.setText(String.valueOf(citasPendientes));
        citasCompletasCli.setText(String.valueOf(citasCompletadas));
        totalMascotasCli.setText(String.valueOf(totalMascotas));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        citasPendientesCli = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        totalMascotasCli = new javax.swing.JLabel();
        citasCompletasCli = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        citasPendientesCli.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        citasPendientesCli.setForeground(new java.awt.Color(0, 153, 255));
        citasPendientesCli.setText("-------");
        add(citasPendientesCli, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 110, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 153, 255));
        jLabel5.setText("Total Mascotas");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 220, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 153, 255));
        jLabel6.setText("Citas Completadas");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 153, 255));
        jLabel7.setText("Citas Pendientes");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 80, -1, -1));

        totalMascotasCli.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        totalMascotasCli.setForeground(new java.awt.Color(0, 153, 255));
        totalMascotasCli.setText("-------");
        add(totalMascotasCli, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 260, -1, -1));

        citasCompletasCli.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        citasCompletasCli.setForeground(new java.awt.Color(0, 153, 255));
        citasCompletasCli.setText("-------");
        add(citasCompletasCli, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel citasCompletasCli;
    private javax.swing.JLabel citasPendientesCli;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel totalMascotasCli;
    // End of variables declaration//GEN-END:variables
}
