package vista.dashboard;

import javax.swing.JLabel;

public class DashboardAdministrativo extends javax.swing.JPanel {

public DashboardAdministrativo() {
        initComponents();
        inicializarValores();
    }
    
    private void inicializarValores() {
        totalCitasHoyAdministrativo.setText("0");
        totalCitasPendientesAdministrativo.setText("0");
        totalCitasCompletadasHoyAdministrativo.setText("0");
    }
    
    // Getters para los labels (necesarios para el controlador)
    public JLabel getTotalCitasHoyAdministrativo() {
        return totalCitasHoyAdministrativo;
    }
    
    public JLabel getTotalCitasPendientesAdministrativo() {
        return totalCitasPendientesAdministrativo;
    }
    
    public JLabel getTotalCitasCompletadasHoyAdministrativo() {
        return totalCitasCompletadasHoyAdministrativo;
    }
    
    // Método para actualizar todos los datos de una vez
    public void actualizarDatos(int citasPendientesTotales, int citasPendientesHoy, int citasCompletadasHoy) {
        totalCitasPendientesAdministrativo.setText(String.valueOf(citasPendientesTotales));
        totalCitasHoyAdministrativo.setText(String.valueOf(citasPendientesHoy));
        totalCitasCompletadasHoyAdministrativo.setText(String.valueOf(citasCompletadasHoy));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        totalCitasPendientesAdministrativo = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        totalCitasHoyAdministrativo = new javax.swing.JLabel();
        totalCitasCompletadasHoyAdministrativo = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(700, 400));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 153, 255));
        jLabel2.setText("Total Citas Completadas Hoy");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 250, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 153, 255));
        jLabel3.setText("Total Citas Pendientes");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 60, -1, -1));

        totalCitasPendientesAdministrativo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        totalCitasPendientesAdministrativo.setForeground(new java.awt.Color(0, 153, 255));
        totalCitasPendientesAdministrativo.setText("---------------");
        add(totalCitasPendientesAdministrativo, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 110, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 153, 255));
        jLabel5.setText("Total Citas Pendientes Hoy");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, -1, -1));

        totalCitasHoyAdministrativo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        totalCitasHoyAdministrativo.setForeground(new java.awt.Color(0, 153, 255));
        totalCitasHoyAdministrativo.setText("-----------");
        add(totalCitasHoyAdministrativo, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, -1, -1));

        totalCitasCompletadasHoyAdministrativo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        totalCitasCompletadasHoyAdministrativo.setForeground(new java.awt.Color(0, 153, 255));
        totalCitasCompletadasHoyAdministrativo.setText("---------------");
        add(totalCitasCompletadasHoyAdministrativo, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 300, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel totalCitasCompletadasHoyAdministrativo;
    private javax.swing.JLabel totalCitasHoyAdministrativo;
    private javax.swing.JLabel totalCitasPendientesAdministrativo;
    // End of variables declaration//GEN-END:variables
}
