/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista.dashboard;

import javax.swing.JLabel;

/**
 *
 * @author jhona
 */
public class DashboardAdministrador extends javax.swing.JPanel {

    public DashboardAdministrador() {
        initComponents();
        // Inicializar con valores por defecto
        inicializarValores();
    }
    
    private void inicializarValores() {
        totalUsuariosAdmin.setText("0");
        totalClientesAdmin.setText("0");
        totalCitasPendientesAdmin.setText("0");
    }
    
    // Getters para obtener los labels (los necesita el controlador)
    public JLabel getTotalUsuariosAdmin() {
        return totalUsuariosAdmin;
    }
    
    public JLabel getTotalClientesAdmin() {
        return totalClientesAdmin;
    }
    
    public JLabel getTotalCitasPendientesAdmin() {
        return totalCitasPendientesAdmin;
    }
    
    // Método para actualizar todos los datos de una vez
    public void actualizarDatos(int totalUsuarios, int totalClientes, int citasPendientes) {
        totalUsuariosAdmin.setText(String.valueOf(totalUsuarios));
        totalClientesAdmin.setText(String.valueOf(totalClientes));
        totalCitasPendientesAdmin.setText(String.valueOf(citasPendientes));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        totalCitasPendientesAdmin = new javax.swing.JLabel();
        totalUsuariosAdmin = new javax.swing.JLabel();
        totalClientesAdmin = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        totalCitasPendientesAdmin.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        totalCitasPendientesAdmin.setForeground(new java.awt.Color(0, 153, 255));
        totalCitasPendientesAdmin.setText("Citas Pendientes");
        add(totalCitasPendientesAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 230, -1, -1));

        totalUsuariosAdmin.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        totalUsuariosAdmin.setForeground(new java.awt.Color(0, 153, 255));
        totalUsuariosAdmin.setText("Total Usuarios");
        add(totalUsuariosAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, -1, -1));

        totalClientesAdmin.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        totalClientesAdmin.setForeground(new java.awt.Color(0, 153, 255));
        totalClientesAdmin.setText("Total Clientes");
        add(totalClientesAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 110, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 153, 255));
        jLabel4.setText("Total Usuarios");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 153, 255));
        jLabel5.setText("Total Clientes");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 60, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 153, 255));
        jLabel6.setText("Citas Pendientes");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 190, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel totalCitasPendientesAdmin;
    private javax.swing.JLabel totalClientesAdmin;
    private javax.swing.JLabel totalUsuariosAdmin;
    // End of variables declaration//GEN-END:variables
}
